export const DELETE_BOOKING = "DELETE_BOOKING";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL";

export const ADD_BOOKING = "ADD_BOOKING";
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_FAIL = "ADD_BOOKING_FAIL";

export const BOOKING = "BOOKING";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAIL = "BOOKING_FAIL";

export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_FAIL = "UPDATE_BOOKING_FAIL";
